trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  armServiceConnection: "azure-connection"
  dockerServiceConnection: "azrdocker-connection"
  imageName: "vicshop-fe"
  rgName: "rg-vic-eshop"
  containerAppName: "swa-vicshop"
  tag: "$(Build.BuildId)"

stages:
  - stage: BuildAndPush
    displayName: "Build and Push Docker Image"
    jobs:
      - job: BuildAndPushJob
        displayName: "Build and Push Job"
        steps:
          - checkout: self
            displayName: "Checkout"

          # Fetch docker-username from Key Vault
          - task: AzureKeyVault@2
            displayName: "Fetch secrets from Key Vault (kv-vic-shop)"
            inputs:
              azureSubscription: "$(armServiceConnection)"
              KeyVaultName: "kv-vic-shop"
              SecretsFilter: "docker-username"
              RunAsPreJob: true

          # Build the Vite app
          - task: NodeTool@0
            displayName: "Use Node 20"
            inputs:
              versionSpec: "20.x"

          - script: |
              set -e
              cd Frontend
              npm ci
              npm run build
            displayName: "Build Vite/React (Frontend)"

          # Docker Hub login
          - task: Docker@2
            displayName: "Login to Docker registry"
            inputs:
              containerRegistry: "$(dockerServiceConnection)"
              command: "login"

          # Build and push Docker image
          - task: Docker@2
            displayName: "Build and push Docker image"
            inputs:
              command: buildAndPush
              repository: "$(docker-username)/$(imageName)"
              tags: |
                $(tag)
                latest
              dockerfile: Frontend/Dockerfile
              buildContext: .
              containerRegistry: "$(dockerServiceConnection)"

  - stage: Deploy
    displayName: "Deploy to Azure Container App"
    dependsOn: BuildAndPush
    jobs:
      - job: DeployJob
        displayName: "Deploy Job"
        steps:
          - task: AzureCLI@2
            displayName: "Deploy to Azure Container App (swa-vicshop)"
            inputs:
              azureSubscription: "$(armServiceConnection)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail

                IMAGE="$(docker-username)/$(imageName):$(tag)"
                echo "Deploying image: ${IMAGE}"

                az extension add --name containerapp --upgrade

                az containerapp update \
                  --name "$(containerAppName)" \
                  --resource-group "$(rgName)" \
                  --image "${IMAGE}"