trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  armServiceConnection: "azure-connection"
  imageName: "vicshop-fe"
  containerAppName: "swa-vicshop"
  tag: "$(Build.BuildId)"

steps:
  - checkout: self
    displayName: "Checkout"

  # Fetch docker-username and docker-password from Key Vault
  - task: AzureKeyVault@2
    displayName: "Fetch secrets from Key Vault (kv-vic-shop)"
    inputs:
      azureSubscription: "$(armServiceConnection)"
      KeyVaultName: "kv-vic-shop"
      SecretsFilter: "docker-username,docker-password"
      RunAsPreJob: true

  # Build the Vite app (optional but recommended to fail fast before docker build)
  - task: NodeTool@0
    displayName: "Use Node 20"
    inputs:
      versionSpec: "20.x"

  - script: |
      set -e
      
      npm ci
      npm run build
    displayName: "Build Vite/React (Frontend)"

  # Docker Hub login
  - task: Docker@2
    displayName: "Login to Docker registry"
    inputs:
      command: login
      containerRegistry: azrdocker-connection

  # Build and push Docker image
  - task: Docker@2
    inputs:
      containerRegistry: 'azrdocker-connection'
      repository: "$(imageName)"
      command: 'build'
      Dockerfile: '**/Dockerfile'

  - task: Docker@2
    inputs:
      containerRegistry: 'azrdocker-connection'
      repository: "$(imageName)"
      tags: |
        $(tag)
        latest
      command: 'push'

  - task: Docker@2
    displayName: "Build and push Docker image"
    inputs:
      command: buildAndPush
      repository: "$(imageName)"
      tags: |
        $(tag)
        latest
      dockerfile: Frontend/Dockerfile
      buildContext: .
      containerRegistry: azrdocker-connection

  # Deploy: update Azure Container App image
  - task: AzureCLI@2
    displayName: "Deploy to Azure Container App (swa-vicshop)"
    inputs:
      azureSubscription: "$(armServiceConnection)"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        IMAGE="$(docker-username)/$(imageName):$(tag)"
        echo "Deploying image: ${IMAGE}"

        az extension add --name containerapp --upgrade

        az containerapp update \
          --name "$(containerAppName)" \
          --resource-group "<AZURE_RESOURCE_GROUP>" \
          --image "${IMAGE}"